[default]
NAME = ""
SECRET_KEY = ""
DEBUG = true
ALLOWED_HOSTS = []
DEFAULT_SETTINGS_PATHES = ['settings.toml', '.secrets.toml']
DATABASE_USERNAME = ""
DATABASE_NAME = ""

[development]
NAME = "developer"
DEBUG = true
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]
DATABASE_USERNAME = "postgres"
DATABASE_NAME = "lifequality"

[production]
NAME = "admin"
DEBUG = false
SECRET_KEY = "xxx"
ALLOWED_HOSTS  = ["127.0.0.1", "localhost", "mininscode.heroku.com"]
DATABASE_USERNAME = "postgres"
DATABASE_NAME = "lifequality"
