"""rev7-test

Revision ID: 00207e455204
Revises: ef3b6b649db4
Create Date: 2022-08-03 19:48:24.778493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00207e455204'
down_revision = 'ef3b6b649db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
