"""rev11

Revision ID: 016fe5514ce2
Revises: 5c2aeacc7882
Create Date: 2022-08-04 23:54:59.012716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016fe5514ce2'
down_revision = '5c2aeacc7882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
