"""rev2

Revision ID: 04e73b99be27
Revises: da048302039c
Create Date: 2022-08-15 17:46:10.965147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e73b99be27'
down_revision = 'da048302039c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_client_request_with_consultation',
    sa.Column('client_request_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('client_request_id', 'consultation_id')
    )
    op.create_table('association_client_request_with_contractor',
    sa.Column('client_request_id', sa.BigInteger(), nullable=False),
    sa.Column('contractor_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('client_request_id', 'contractor_id')
    )
    op.create_table('association_client_request_with_employee',
    sa.Column('client_request_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('client_request_id', 'employee_id')
    )
    op.create_table('association_client_request_with_work',
    sa.Column('client_request_id', sa.BigInteger(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('client_request_id', 'work_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_client_request_with_work')
    op.drop_table('association_client_request_with_employee')
    op.drop_table('association_client_request_with_contractor')
    op.drop_table('association_client_request_with_consultation')
    # ### end Alembic commands ###
