"""rev5-test

Revision ID: 06ff3d69e2ef
Revises: 6a9eadb84b79
Create Date: 2022-08-03 19:46:47.020039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ff3d69e2ef'
down_revision = '6a9eadb84b79'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
