"""rev3-test

Revision ID: 1bc0fb33f15c
Revises: 00980bbee5d2
Create Date: 2022-08-03 19:41:48.567469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc0fb33f15c'
down_revision = '00980bbee5d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'citizens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citizens', type_='foreignkey')
    op.drop_column('citizens', 'user_id')
    # ### end Alembic commands ###
