"""rev15

Revision ID: 37ff7abdd928
Revises: 1659355ac4e3
Create Date: 2022-08-05 10:06:34.274950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ff7abdd928'
down_revision = '1659355ac4e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_sources',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_sources_id'), 'request_sources', ['id'], unique=False)
    op.drop_index('ix_sources_id', table_name='sources')
    op.drop_table('sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sources_pkey')
    )
    op.create_index('ix_sources_id', 'sources', ['id'], unique=False)
    op.drop_index(op.f('ix_request_sources_id'), table_name='request_sources')
    op.drop_table('request_sources')
    # ### end Alembic commands ###
