"""revision_13: comment_model

Revision ID: 47276ccf5539
Revises: 4c667d1aecaa
Create Date: 2022-08-09 15:48:53.828033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47276ccf5539'
down_revision = '4c667d1aecaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('citizen_comments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.String(length=250), nullable=False),
    sa.Column('author', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citizen_request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_request_id'], ['citizen_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_comments_id'), 'citizen_comments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_comments_id'), table_name='citizen_comments')
    op.drop_table('citizen_comments')
    # ### end Alembic commands ###
