"""revision_12: request_document_model

Revision ID: 4c667d1aecaa
Revises: 6fd7a9fc1ed0
Create Date: 2022-08-09 12:01:35.689246

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c667d1aecaa'
down_revision = '6fd7a9fc1ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests_documents',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('documentt_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citizen_request_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_documents_id'), 'requests_documents', ['id'], unique=False)
    op.drop_index('ix_work_orders_id', table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('citizen_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('contractor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['citizen_request_id'], ['citizen_requests.id'], name='work_orders_citizen_request_id_fkey'),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], name='work_orders_contractor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='work_orders_pkey')
    )
    op.create_index('ix_work_orders_id', 'work_orders', ['id'], unique=False)
    op.drop_index(op.f('ix_requests_documents_id'), table_name='requests_documents')
    op.drop_table('requests_documents')
    # ### end Alembic commands ###
