"""revision_1: init

Revision ID: 536ef6115285
Revises: 
Create Date: 2022-08-06 16:37:59.841212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '536ef6115285'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.drop_constraint('houses_condition_fkey', 'houses', type_='foreignkey')
    op.create_foreign_key(None, 'houses', 'house_conditions', ['condition_id'], ['id'])
    op.drop_column('houses', 'condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('condition', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.create_foreign_key('houses_condition_fkey', 'houses', 'house_conditions', ['condition'], ['id'])
    op.drop_column('houses', 'condition_id')
    # ### end Alembic commands ###
