"""rev10

Revision ID: 5c2aeacc7882
Revises: af7a5eb15099
Create Date: 2022-08-04 17:58:36.792249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c2aeacc7882'
down_revision = 'af7a5eb15099'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_conditions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_house_conditions_id'), 'house_conditions', ['id'], unique=False)
    op.add_column('houses', sa.Column('district', sa.String(length=50), nullable=False))
    op.add_column('houses', sa.Column('condition', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'houses', 'house_conditions', ['condition'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.drop_column('houses', 'condition')
    op.drop_column('houses', 'district')
    op.drop_index(op.f('ix_house_conditions_id'), table_name='house_conditions')
    op.drop_table('house_conditions')
    # ### end Alembic commands ###
