"""rev5

Revision ID: 5f31e9688235
Revises: 
Create Date: 2022-09-01 11:22:21.600229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f31e9688235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_table('association_client_request_with_consultation',
    sa.Column('client_request_id', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['client_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.PrimaryKeyConstraint('client_request_id', 'consultation_id')
    )
    op.create_foreign_key(None, 'association_consultation_with_employee', 'consultations', ['consultation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'association_consultation_with_employee', type_='foreignkey')
    op.drop_table('association_client_request_with_consultation')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_table('consultations')
    # ### end Alembic commands ###
