"""rev4-test

Revision ID: 6a9eadb84b79
Revises: 1bc0fb33f15c
Create Date: 2022-08-03 19:44:38.373223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9eadb84b79'
down_revision = '1bc0fb33f15c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('citizens_passports', sa.Column('citizen_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'citizens_passports', 'citizens', ['citizen_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'citizens_passports', type_='foreignkey')
    op.drop_column('citizens_passports', 'citizen_id')
    # ### end Alembic commands ###
