"""revision_11: work_order_model

Revision ID: 6fd7a9fc1ed0
Revises: 3ed8f460d3a4
Create Date: 2022-08-09 10:30:51.280272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd7a9fc1ed0'
down_revision = '3ed8f460d3a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('citizen_request_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_request_id'], ['citizen_requests.id'], ),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_id'), table_name='work_orders')
    op.drop_table('work_orders')
    # ### end Alembic commands ###
