"""rev6

Revision ID: 9497908b9210
Revises: 5f31e9688235
Create Date: 2022-09-01 11:27:55.013145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9497908b9210'
down_revision = '5f31e9688235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
