"""rev3

Revision ID: 9927fe826369
Revises: 04e73b99be27
Create Date: 2022-08-16 14:28:19.578053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9927fe826369'
down_revision = '04e73b99be27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_consultation_with_employee',
    sa.Column('consultation_id', sa.BigInteger(), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('consultation_id', 'employee_id')
    )
    op.create_table('association_contractor_with_house',
    sa.Column('contractor_id', sa.BigInteger(), nullable=False),
    sa.Column('house_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('contractor_id', 'house_id')
    )
    op.create_table('association_contractor_with_work',
    sa.Column('contractor_id', sa.BigInteger(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('contractor_id', 'work_id')
    )
    op.create_table('association_contract_with_work',
    sa.Column('contract_id', sa.BigInteger(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('contract_id', 'work_id')
    )
    op.create_table('association_meeting_with_client',
    sa.Column('meeting_id', sa.BigInteger(), nullable=False),
    sa.Column('citizen_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('meeting_id', 'citizen_id')
    )
    op.create_table('association_request_document_with work',
    sa.Column('request_document_id', sa.BigInteger(), nullable=False),
    sa.Column('work_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['request_document_id'], ['requests_documents.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('request_document_id', 'work_id')
    )
    op.drop_constraint('consultations_employee_id_fkey', 'consultations', type_='foreignkey')
    op.drop_column('consultations', 'employee_id')
    op.add_column('requests_documents', sa.Column('document_type', sa.String(length=50), nullable=False))
    op.drop_column('requests_documents', 'documentt_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests_documents', sa.Column('documentt_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('requests_documents', 'document_type')
    op.add_column('consultations', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('consultations_employee_id_fkey', 'consultations', 'employees', ['employee_id'], ['id'])
    op.drop_table('association_request_document_with work')
    op.drop_table('association_meeting_with_client')
    op.drop_table('association_contract_with_work')
    op.drop_table('association_contractor_with_work')
    op.drop_table('association_contractor_with_house')
    op.drop_table('association_consultation_with_employee')
    # ### end Alembic commands ###
