"""revision_9: client_request_model

Revision ID: d393d9a46100
Revises: 
Create Date: 2022-08-09 10:28:59.264163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd393d9a46100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('is_emergency', sa.Boolean(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_id'), 'works', ['id'], unique=False)
    op.create_table('citizen_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('citizen_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('request_source', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('fact_duration', sa.DateTime(), nullable=False),
    sa.Column('request_status', sa.Integer(), nullable=False),
    sa.Column('citizen_feedback', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['citizen_id'], ['citizens.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['call_records.id'], ),
    sa.ForeignKeyConstraint(['request_source'], ['request_sources.id'], ),
    sa.ForeignKeyConstraint(['request_status'], ['request_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_citizen_requests_id'), 'citizen_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citizen_requests_id'), table_name='citizen_requests')
    op.drop_table('citizen_requests')
    op.drop_index(op.f('ix_works_id'), table_name='works')
    op.drop_table('works')
    # ### end Alembic commands ###
