"""rev16

Revision ID: dbf131695093
Revises: 37ff7abdd928
Create Date: 2022-08-06 09:30:50.704120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf131695093'
down_revision = '37ff7abdd928'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractors_id'), 'contractors', ['id'], unique=False)
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('contract_number', sa.Integer(), nullable=True),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('contract_file', sa.String(length=250), nullable=False),
    sa.Column('house_id', sa.Integer(), nullable=False),
    sa.Column('contractor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['contractor_id'], ['contractors.id'], ),
    sa.ForeignKeyConstraint(['house_id'], ['houses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_id'), 'contracts', ['id'], unique=False)
    op.add_column('houses', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.drop_constraint('houses_condition_fkey', 'houses', type_='foreignkey')
    op.create_foreign_key(None, 'houses', 'house_conditions', ['condition_id'], ['id'])
    op.drop_column('houses', 'condition')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('houses', sa.Column('condition', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'houses', type_='foreignkey')
    op.create_foreign_key('houses_condition_fkey', 'houses', 'house_conditions', ['condition'], ['id'])
    op.drop_column('houses', 'condition_id')
    op.drop_index(op.f('ix_contracts_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_contractors_id'), table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
