"""rev6-test

Revision ID: ef3b6b649db4
Revises: 06ff3d69e2ef
Create Date: 2022-08-03 19:47:43.226136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3b6b649db4'
down_revision = '06ff3d69e2ef'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
